name: Deploy Project
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup golang
        uses: actions/setup-go@main
        with:
          go-version: 1.17.4

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: GOOS=js GOARCH=wasm go build -ldflags "-s -w" -o page/game.wasm .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./page